[package]
name = "gfwc"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
categories = ["command-line-utilities"]
description = "Unix command line wc tool in Rust for [ccwc](https://codingchallenges.fyi/challenges/challenge-wc/)"

[dependencies]
